const countryLeaders = {
    "Afghanistan": "Taliban Leadership",
    "Albania": "Edi Rama (Prime Minister)",
    "Algeria": "Abdelmadjid Tebboune (President)",
    "Angola": "João Lourenço (President)",
    "Argentina": "Javier Milei (President)",
    "Australia": "Anthony Albanese (Prime Minister)",
    "Austria": "Karl Nehammer (Chancellor)",
    "Azerbaijan": "Ilham Aliyev (President)",
    "Bangladesh": "Sheikh Hasina (Prime Minister)",
    "Belarus": "Alexander Lukashenko (President)",
    "Belgium": "Alexander De Croo (Prime Minister)",
    "Bolivia": "Luis Arce (President)",
    "Brazil": "Luiz Inácio Lula da Silva (President)",
    "Bulgaria": "Nikolai Denkov (Prime Minister)",
    "Cambodia": "Hun Manet (Prime Minister)",
    "Canada": "Justin Trudeau (Prime Minister)",
    "Chile": "Gabriel Boric (President)",
    "China": "Xi Jinping (President)",
    "Colombia": "Gustavo Petro (President)",
    "Costa Rica": "Rodrigo Chaves (President)",
    "Croatia": "Andrej Plenković (Prime Minister)",
    "Cuba": "Miguel Díaz-Canel (President)",
    "Czech Republic": "Petr Fiala (Prime Minister)",
    "Denmark": "Mette Frederiksen (Prime Minister)",
    "Egypt": "Abdel Fattah el-Sisi (President)",
    "Ethiopia": "Abiy Ahmed (Prime Minister)",
    "Finland": "Alexander Stubb (President)",
    "France": "Gabriel Attal (Prime Minister)",
    "Germany": "Olaf Scholz (Chancellor)",
    "Greece": "Kyriakos Mitsotakis (Prime Minister)",
    "Hungary": "Viktor Orbán (Prime Minister)",
    "Iceland": "Katrín Jakobsdóttir (Prime Minister)",
    "India": "Narendra Modi (Prime Minister)",
    "Indonesia": "Joko Widodo (President)",
    "Iran": "Ebrahim Raisi (President)",
    "Iraq": "Mohammed Shia' Al Sudani (Prime Minister)",
    "Ireland": "Simon Harris (Prime Minister)",
    "Israel": "Benjamin Netanyahu (Prime Minister)",
    "Italy": "Giorgia Meloni (Prime Minister)",
    "Japan": "Fumio Kishida (Prime Minister)",
    "Kazakhstan": "Kassym-Jomart Tokayev (President)",
    "Kenya": "William Ruto (President)",
    "Kuwait": "Sheikh Meshal Al-Ahmad Al-Jaber Al-Sabah (Emir)",
    "Lebanon": "Najib Mikati (Prime Minister)",
    "Libya": "Abdul Hamid Dbeibeh (Prime Minister)",
    "Malaysia": "Anwar Ibrahim (Prime Minister)",
    "Mexico": "Andrés Manuel López Obrador (President)",
    "Morocco": "Aziz Akhannouch (Prime Minister)",
    "Myanmar": "Min Aung Hlaing (Military Leader)",
    "Netherlands": "Mark Rutte (Prime Minister)",
    "New Zealand": "Christopher Luxon (Prime Minister)",
    "Nigeria": "Bola Tinubu (President)",
    "North Korea": "Kim Jong-un (Supreme Leader)",
    "Norway": "Jonas Gahr Støre (Prime Minister)",
    "Pakistan": "Shehbaz Sharif (Prime Minister)",
    "Philippines": "Bongbong Marcos (President)",
    "Poland": "Donald Tusk (Prime Minister)",
    "Portugal": "Luís Montenegro (Prime Minister)",
    "Qatar": "Sheikh Tamim bin Hamad Al Thani (Emir)",
    "Romania": "Ion-Marcel Ciolacu (Prime Minister)",
    "Russia": "Vladimir Putin (President)",
    "Saudi Arabia": "Mohammed bin Salman (Crown Prince)",
    "Serbia": "Ana Brnabić (Prime Minister)",
    "Singapore": "Lawrence Wong (Prime Minister)",
    "South Africa": "Cyril Ramaphosa (President)",
    "South Korea": "Han Duck-soo (Prime Minister)",
    "Spain": "Pedro Sánchez (Prime Minister)",
    "Sweden": "Ulf Kristersson (Prime Minister)",
    "Switzerland": "Viola Amherd (President)",
    "Syria": "Bashar al-Assad (President)",
    "Taiwan": "Lai Ching-te (President)",
    "Thailand": "Srettha Thavisin (Prime Minister)",
    "Turkey": "Recep Tayyip Erdoğan (President)",
    "Ukraine": "Volodymyr Zelenskyy (President)",
    "United Arab Emirates": "Mohammed bin Zayed Al Nahyan (President)",
    "United Kingdom": "Rishi Sunak (Prime Minister)",
    "United States": "Joe Biden (President)",
    "Venezuela": "Nicolás Maduro (President)",
    "Vietnam": "Võ Văn Thưởng (President)"
};

export default countryLeaders;