const countryTimezones = {
    "Afghanistan": "Asia/Kabul",
    "Albania": "Europe/Tirane",
    "Algeria": "Africa/Algiers",
    "Angola": "Africa/Luanda",
    "Argentina": "America/Argentina/Buenos_Aires",
    "Australia": "Australia/Sydney",
    "Austria": "Europe/Vienna",
    "Azerbaijan": "Asia/Baku",
    "Bangladesh": "Asia/Dhaka",
    "Belarus": "Europe/Minsk",
    "Belgium": "Europe/Brussels",
    "Brazil": "America/Sao_Paulo",
    "Canada": "America/Toronto",
    "China": "Asia/Shanghai",
    "Egypt": "Africa/Cairo",
    "France": "Europe/Paris",
    "Germany": "Europe/Berlin",
    "Greece": "Europe/Athens",
    "India": "Asia/Kolkata",
    "Indonesia": "Asia/Jakarta",
    "Iran": "Asia/Tehran",
    "Iraq": "Asia/Baghdad",
    "Ireland": "Europe/Dublin",
    "Israel": "Asia/Jerusalem",
    "Italy": "Europe/Rome",
    "Japan": "Asia/Tokyo",
    "Kazakhstan": "Asia/Almaty",
    "Kenya": "Africa/Nairobi",
    "Malaysia": "Asia/Kuala_Lumpur",
    "Mexico": "America/Mexico_City",
    "Morocco": "Africa/Casablanca",
    "Netherlands": "Europe/Amsterdam",
    "New Zealand": "Pacific/Auckland",
    "Nigeria": "Africa/Lagos",
    "Norway": "Europe/Oslo",
    "Pakistan": "Asia/Karachi",
    "Philippines": "Asia/Manila",
    "Poland": "Europe/Warsaw",
    "Portugal": "Europe/Lisbon",
    "Russia": "Europe/Moscow",
    "Saudi Arabia": "Asia/Riyadh",
    "Singapore": "Asia/Singapore",
    "South Africa": "Africa/Johannesburg",
    "South Korea": "Asia/Seoul",
    "Spain": "Europe/Madrid",
    "Sweden": "Europe/Stockholm",
    "Switzerland": "Europe/Zurich",
    "Thailand": "Asia/Bangkok",
    "Turkey": "Europe/Istanbul",
    "Ukraine": "Europe/Kiev",
    "United Arab Emirates": "Asia/Dubai",
    "United Kingdom": "Europe/London",
    "United States": "America/New_York",
    "Vietnam": "Asia/Ho_Chi_Minh"
};

export default countryTimezones;